import type { Product, Review } from "./types";

/**
 * 참신한하루 실제 제품 데이터 (예전 브랜드 홈페이지 data/products.js 기준).
 * ⚠️ price는 예시값입니다 — 실제 판매가로 교체하세요(원본에는 가격이 없었음).
 * 문구는 원료 중심이며 질병의 예방·치료를 단정하지 않습니다.
 */
const BASE_CAUTION =
  "특정 원료에 알레르기가 있는 분은 원재료를 확인하세요. 임신·수유 중이거나 질환이 있는 분, 약을 복용 중인 분은 전문가와 상담 후 섭취하세요.";
const HACCP_ORIGIN = "대한민국 · HACCP 인증 시설 제조 (원료 일부 수입)";

export const PRODUCTS: Product[] = [
  {
    id: "daily-dietary-fiber",
    slug: "daily-dietary-fiber",
    name: "데일리 식이섬유 정",
    engName: "Daily Dietary Fiber Tablets",
    brand: "참신한하루",
    summary: "치커리 식이섬유 고함량, 하루 한 번 부담 없는 장 관리",
    category: "장건강",
    price: 24900,
    salePrice: 21900,
    accent: "#6f8f6a",
    image: "/products/product-01.jpg",
    servings: "600mg × 120정 (72g)",
    ingredients: [
      "화이브로우즈 에프90 (치커리식이섬유, 식이섬유 80%) 43,200mg",
      "난소화성말토덱스트린 (식이섬유 85%) 8,640mg",
      "프락토올리고당 7,200mg",
      "양배추추출분말 3,600mg",
    ],
    features: [
      "치커리 유래 식이섬유를 넉넉하게 담은 데일리 설계",
      "프락토올리고당 & 난소화성말토덱스트린 함께 구성",
      "삼키기 편한 작은 정제, 하루 섭취량 간편",
    ],
    recommend: ["채소 섭취가 부족한 분", "규칙적인 장 활동을 챙기고 싶은 분", "가벼운 하루를 원하는 분"],
    intake: "1일 2정을 물과 함께 충분히 섭취하세요. (자세한 섭취량은 제품 표기 참고)",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION,
    stock: 180,
    rating: 4.8,
    reviewCount: 214,
    subscription: { enabled: true, discountPercent: 15, intervalDays: 30 },
    badges: ["치커리 식이섬유", "작은 정제"],
    isBest: true,
  },
  {
    id: "mugunghwa-fit-on",
    slug: "mugunghwa-fit-on",
    name: "무궁화추출물 핏온 정",
    engName: "Mugunghwa Extract Fit On Pill",
    brand: "참신한하루",
    summary: "무궁화 추출 복합분말을 담은 핏 관리 파트너",
    category: "다이어트",
    price: 29900,
    accent: "#cf7f43",
    image: "/products/product-02.jpg",
    servings: "600mg × 60정 (36g)",
    ingredients: ["무궁화추출복합분말 90%", "무궁화꽃 추출분말 5%"],
    features: ["무궁화 추출 복합분말 고배합", "식이 조절 중 함께 챙기기 좋은 구성", "간편한 정제 타입"],
    recommend: ["체중 관리에 관심 있는 분", "가벼운 컨디션을 원하는 분", "식단 관리를 함께 하는 분"],
    intake: "1일 2정을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION,
    stock: 90,
    rating: 4.6,
    reviewCount: 78,
    subscription: { enabled: true, discountPercent: 12, intervalDays: 30 },
    badges: ["무궁화 복합분말", "핏 관리"],
  },
  {
    id: "triella-collagen-biotin",
    slug: "triella-collagen-biotin",
    name: "트리엘라 초저분자 어린콜라겐 펩타이드 비오틴 플러스",
    engName: "TRIELLA Low Molecular Collagen Peptide + Biotin",
    brand: "참신한하루",
    summary: "초저분자 피쉬 콜라겐 5,400mg + 비오틴, 안에서부터 관리",
    category: "뷰티",
    price: 42000,
    salePrice: 36900,
    accent: "#b56a86",
    image: "/products/product-03.jpg",
    servings: "450mg × 120정 (54g)",
    ingredients: ["콜라겐 추출물 [저분자 피쉬콜라겐 5,400mg, 비오틴 540μg] 99%"],
    features: ["초저분자 피쉬 콜라겐 고함량", "비오틴을 더한 이너뷰티 설계", "프리미엄 서브브랜드 TRIELLA"],
    recommend: ["속부터 탄력을 챙기고 싶은 분", "모발·손톱 건강에 관심 있는 분", "데일리 이너뷰티를 원하는 분"],
    intake: "1일 2정을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION + " 어류 알레르기가 있는 분은 주의하세요.",
    stock: 140,
    rating: 4.9,
    reviewCount: 326,
    subscription: { enabled: true, discountPercent: 10, intervalDays: 30 },
    badges: ["초저분자 콜라겐", "비오틴 함유"],
    isBest: true,
  },
  {
    id: "paradise-grain-burning",
    slug: "paradise-grain-burning",
    name: "파라다이스 그레인 버닝 원데이즈 정",
    engName: "Paradise Grain Burning Tablets",
    brand: "참신한하루",
    summary: "파라다이스 그레인 추출분말을 담은 원데이 버닝 설계",
    category: "다이어트",
    price: 32900,
    accent: "#cf7f43",
    image: "/products/product-04.jpg",
    servings: "600mg × 120정 (72g)",
    ingredients: ["파라다이스 그레인 혼합물 [파라다이스 그레인 추출분말 3,600mg] 99%"],
    features: ["파라다이스 그레인 추출분말 고배합", "하루 한 번 원데이즈 컨셉", "활동적인 라이프스타일과 함께"],
    recommend: ["다이어트를 준비하는 분", "활력 있는 하루를 원하는 분", "간편한 관리 루틴을 찾는 분"],
    intake: "1일 2정을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION,
    stock: 76,
    rating: 4.6,
    reviewCount: 64,
    subscription: { enabled: true, discountPercent: 12, intervalDays: 30 },
    badges: ["파라다이스 그레인", "원데이즈"],
  },
  {
    id: "fermented-oyster-kids",
    slug: "fermented-oyster-kids",
    name: "발효굴 추출분말 & 유산균 정",
    engName: "Fermented Oyster Extract & Probiotics (Kids)",
    brand: "참신한하루",
    summary: "발효굴 추출분말 6,480mg + 22종 혼합유산균, 우리 아이 데일리",
    category: "키즈",
    price: 27900,
    accent: "#6d93b0",
    image: "/products/product-05.jpg",
    servings: "600mg × 60정 (36g)",
    ingredients: ["발효굴추출분말 6,480mg", "22종 혼합유산균 360,000μg"],
    features: ["발효굴 추출분말 고함량", "22종 혼합유산균 함께 구성", "아이도 먹기 편한 설계"],
    recommend: ["성장기 아이의 데일리 관리", "장 건강을 함께 챙기고 싶은 가족", "온 가족 유산균을 찾는 분"],
    intake: "아이 연령에 맞춰 하루 권장량을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution:
      BASE_CAUTION + " 갑각류·어패류 알레르기가 있는 분은 주의하고, 어린이는 보호자와 함께 확인하세요.",
    stock: 88,
    rating: 4.8,
    reviewCount: 152,
    subscription: { enabled: true, discountPercent: 12, intervalDays: 30 },
    badges: ["22종 유산균", "온 가족"],
  },
  {
    id: "alpha-cd-one-days",
    slug: "alpha-cd-one-days",
    name: "알파CD 알파시클로덱스트린 원데이즈",
    engName: "α-Cyclodextrin One Days",
    brand: "참신한하루",
    summary: "알파시클로덱스트린 2,700mg, 식이 관리 원데이 파트너",
    category: "다이어트",
    price: 29900,
    accent: "#cf7f43",
    image: "/products/product-06.jpg",
    servings: "450mg × 120정 (54g)",
    ingredients: ["알파CD 추출물 [α-시클로덱스트린 2,700mg] 99%"],
    features: ["알파시클로덱스트린(식이섬유) 고함량", "하루 한 번 원데이즈 설계", "식이 조절과 함께"],
    recommend: ["식이 관리에 관심 있는 분", "가벼운 식습관을 원하는 분", "간편 관리 루틴을 찾는 분"],
    intake: "1일 1정을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION,
    stock: 110,
    rating: 4.7,
    reviewCount: 71,
    subscription: { enabled: true, discountPercent: 12, intervalDays: 30 },
    badges: ["알파CD", "원데이즈"],
    isNew: true,
  },
  {
    id: "plant-melatonin-tart-cherry",
    slug: "plant-melatonin-tart-cherry",
    name: "식물성 멜라토닌 피스타치오 타트체리 정",
    engName: "Premium Melatonin Tablet",
    brand: "참신한하루",
    summary: "피스타치오 유래 멜라토닌 + 타트체리, 편안한 밤을 위한 설계",
    category: "컨디션",
    price: 28900,
    accent: "#8a7f53",
    image: "/products/product-07.jpg",
    servings: "600mg × 60정 (36g)",
    ingredients: ["피스타치오 추출분말 (멜라토닌 1% 함유) 33.4%", "타트체리 농축분말 20%"],
    features: ["식물성(피스타치오 유래) 멜라토닌 원료", "타트체리 농축분말을 더한 구성", "잠들기 전 편안한 루틴"],
    recommend: ["편안한 밤을 원하는 분", "생활 리듬이 불규칙한 분", "식물성 원료를 선호하는 분"],
    intake: "취침 30분 전 권장량을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION + " 졸음을 유발할 수 있으니 운전 전에는 피하세요.",
    stock: 64,
    rating: 4.7,
    reviewCount: 118,
    subscription: { enabled: true, discountPercent: 15, intervalDays: 30 },
    badges: ["식물성 멜라토닌", "타트체리"],
    isNew: true,
  },
  {
    id: "green-acerola-vitamin-c",
    slug: "green-acerola-vitamin-c",
    name: "그린 아세로라 유래 비타민C 원데이즈",
    engName: "Green Acerola Vitamin C",
    brand: "참신한하루",
    summary: "아세로라 유래 천연 비타민C, 상큼하게 챙기는 하루 활력",
    category: "비타민·면역",
    price: 21900,
    accent: "#d3a83c",
    image: "/products/product-08.jpg",
    servings: "450mg × 120정 (54g)",
    ingredients: ["그린아세로라 추출분말 [아세로라 유래 비타민C 459mg, 비타민C 10,800mg] 99%"],
    features: ["아세로라 유래 비타민C 원료", "하루 한 번 원데이즈 설계", "상큼한 데일리 비타민"],
    recommend: ["피로한 일상을 보내는 분", "비타민C를 꾸준히 챙기고 싶은 분", "천연 유래 원료를 선호하는 분"],
    intake: "1일 1정을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION,
    stock: 200,
    rating: 4.7,
    reviewCount: 205,
    subscription: { enabled: true, discountPercent: 15, intervalDays: 60 },
    badges: ["아세로라 유래", "원데이즈"],
  },
  {
    id: "khorasan-grain-enzyme",
    slug: "khorasan-grain-enzyme",
    name: "프리미엄 호라산밀 곡물효소 정",
    engName: "Premium Khorasan Wheat Grain Enzyme",
    brand: "참신한하루",
    summary: "카무트(호라산밀) + 치커리 식이섬유 + 곡물효소의 든든한 조합",
    category: "장건강",
    price: 34900,
    accent: "#6f8f6a",
    image: "/products/product-09.jpg",
    servings: "1,000mg × 60정 (60g)",
    ingredients: [
      "호라산밀 (볶은 카무트 분말 100%/캐나다) 6,000mg",
      "치커리식이섬유 30,000mg",
      "15곡 복합발효효소 PR1000 1,800mg",
    ],
    features: ["카무트(호라산밀) 원물 함유", "치커리 식이섬유 고함량", "15곡 복합발효효소 구성"],
    recommend: ["든든한 곡물 관리를 원하는 분", "식이섬유를 넉넉히 챙기고 싶은 분", "속 편한 하루를 원하는 분"],
    intake: "1일 2정을 물과 함께 섭취하세요.",
    origin: "캐나다산 카무트 등 · 국내 HACCP 인증 시설 제조",
    caution: BASE_CAUTION + " 밀 알레르기가 있는 분은 주의하세요.",
    stock: 82,
    rating: 4.7,
    reviewCount: 96,
    subscription: { enabled: true, discountPercent: 12, intervalDays: 30 },
    badges: ["카무트 원물", "15곡 효소"],
    isNew: true,
  },
  {
    id: "papa-flora-ginger",
    slug: "papa-flora-ginger",
    name: "파파 플로라 생강추출물 정",
    engName: "Papa Flora Ginger Extract",
    brand: "참신한하루",
    summary: "생강 추출분말 + 흑마늘, 따뜻하게 챙기는 컨디션",
    category: "컨디션",
    price: 25900,
    accent: "#8a7f53",
    image: "/products/product-10.jpg",
    servings: "600mg × 60정 (36g)",
    ingredients: ["생강추출분말 80%", "흑마늘농축분말 10%", "치커리식이섬유 5%"],
    features: ["생강 추출분말 고배합", "흑마늘 농축분말을 더한 구성", "환절기 컨디션 관리에"],
    recommend: ["환절기 컨디션이 걱정인 분", "따뜻한 관리를 원하는 분", "활력 있는 하루를 원하는 분"],
    intake: "1일 2정을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION,
    stock: 95,
    rating: 4.8,
    reviewCount: 133,
    subscription: { enabled: true, discountPercent: 12, intervalDays: 30 },
    badges: ["생강 추출", "흑마늘"],
  },
  {
    id: "lemon-vitamin-c",
    slug: "lemon-vitamin-c",
    name: "레몬즙 비타민C 정",
    engName: "Lemon Juice Vitamin C Tablets",
    brand: "참신한하루",
    summary: "레몬 과즙분말 80% + 비타민C, 상큼한 데일리 비타민",
    category: "비타민·면역",
    price: 18900,
    accent: "#d3a83c",
    image: "/products/product-11.jpg",
    servings: "600mg × 60정 (36g)",
    ingredients: ["레몬과즙분말 80%", "비타민C 10%"],
    features: ["레몬 과즙분말 고함량", "비타민C를 더한 상큼한 구성", "간편하게 챙기는 정제 타입"],
    recommend: ["상큼한 비타민을 원하는 분", "활력이 필요한 분", "데일리 비타민C를 찾는 분"],
    intake: "1일 2정을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION,
    stock: 160,
    rating: 4.6,
    reviewCount: 88,
    subscription: { enabled: true, discountPercent: 15, intervalDays: 30 },
    badges: ["레몬 과즙", "데일리"],
  },
  {
    id: "liposomal-glutathione",
    slug: "liposomal-glutathione",
    name: "리포좀 글루타치온 정",
    engName: "Liposomal Glutathione Tablet",
    brand: "참신한하루",
    summary: "리포좀 글루타치온 + 비타민C, 안에서부터 맑고 환하게",
    category: "뷰티",
    price: 39000,
    salePrice: 34900,
    accent: "#b56a86",
    image: "/products/product-12.jpg",
    servings: "600mg × 60정 (36g)",
    ingredients: [
      "리포좀 L-글루타치온효모90 1,440mg (글루타치온 1,296mg 함유)",
      "엔게비타GSH 15% (글루타치온 135mg 함유)",
      "비타민C 360mg",
    ],
    features: ["리포좀 코팅 글루타치온 원료", "이중 글루타치온 설계", "비타민C를 더한 이너뷰티 구성"],
    recommend: ["맑고 환한 컨디션을 원하는 분", "이너뷰티를 챙기는 분", "글루타치온을 꾸준히 찾는 분"],
    intake: "1일 2정을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION,
    stock: 120,
    rating: 4.9,
    reviewCount: 241,
    subscription: { enabled: true, discountPercent: 10, intervalDays: 30 },
    badges: ["리포좀 코팅", "이중 글루타치온"],
    isBest: true,
  },
  {
    id: "eggshell-gujeolcho",
    slug: "eggshell-gujeolcho",
    name: "난각막 구아검 가수분해물 구절초 플러스",
    engName: "Premium Guagum Gujeolcho Plus",
    brand: "참신한하루",
    summary: "구절초 + 난각막 + 구아검 가수분해물, 편안한 움직임을 위한 설계",
    category: "컨디션",
    price: 33900,
    accent: "#8a7f53",
    image: "/products/product-13.jpg",
    servings: "450mg × 120정 (54g)",
    ingredients: [
      "난각막 구절초 포뮬러 [구절초추출분말 10,800mg, 난각막수용성분말 2,700mg, 구아검가수분해물 1,080mg] 99%",
    ],
    features: ["난각막(NEM) 수용성 분말 함유", "구절초 추출분말 고배합", "구아검 가수분해물 함께 구성"],
    recommend: ["활동이 많은 분", "편안한 움직임을 원하는 분", "관절 관리를 미리 챙기는 분"],
    intake: "1일 2정을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION + " 계란(난각막) 알레르기가 있는 분은 주의하세요.",
    stock: 70,
    rating: 4.7,
    reviewCount: 84,
    subscription: { enabled: true, discountPercent: 12, intervalDays: 30 },
    badges: ["난각막 NEM", "구절초"],
  },
  {
    id: "acv-probiotics",
    slug: "acv-probiotics",
    name: "애플사이다비니거 사과초모 유산균 정",
    engName: "Apple Cider Vinegar & Probiotics",
    brand: "참신한하루",
    summary: "유기농 사과초모 식초분말 + 22종 유산균, 상큼한 장 관리",
    category: "장건강",
    price: 26900,
    salePrice: 23900,
    accent: "#6f8f6a",
    image: "/products/product-14.jpg",
    servings: "600mg × 60정 (36g)",
    ingredients: ["유기농 사과초모식초분말 25,200mg", "22종 혼합유산균 180mg"],
    features: ["유기농 사과초모(ACV) 식초분말 고함량", "22종 혼합유산균 함께 구성", "번거로운 식초를 간편한 정제로"],
    recommend: ["가벼운 식습관을 원하는 분", "장 건강을 함께 챙기고 싶은 분", "사과초모를 간편하게 먹고 싶은 분"],
    intake: "1일 2정을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION,
    stock: 130,
    rating: 4.8,
    reviewCount: 176,
    subscription: { enabled: true, discountPercent: 12, intervalDays: 30 },
    badges: ["유기농 ACV", "22종 유산균"],
    isBest: true,
  },
  {
    id: "saururus-liriope",
    slug: "saururus-liriope",
    name: "삼백초 맥문동 정",
    engName: "Saururus & Liriope Tablet",
    brand: "참신한하루",
    summary: "삼백초 + 맥문동, 예로부터 즐겨온 원물의 데일리 설계",
    category: "컨디션",
    price: 24900,
    accent: "#8a7f53",
    image: "/products/product-15.jpg",
    servings: "600mg × 60정 (36g)",
    ingredients: ["삼백초추출분말 80%", "맥문동추출분말 4%"],
    features: ["삼백초 추출분말 고배합", "맥문동 추출분말 함께 구성", "데일리로 챙기는 원물 관리"],
    recommend: ["꾸준한 컨디션 관리를 원하는 분", "원물 기반 제품을 선호하는 분", "가벼운 하루를 원하는 분"],
    intake: "1일 2정을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION,
    stock: 85,
    rating: 4.6,
    reviewCount: 57,
    subscription: { enabled: true, discountPercent: 12, intervalDays: 30 },
    badges: ["삼백초", "맥문동"],
  },
  {
    id: "albumin-signature",
    slug: "albumin-signature",
    name: "알부민 정",
    engName: "Albumin Tablet",
    brand: "참신한하루",
    summary: "계란 흰자에서 온 알부민·아미노산을 담은 참신한하루 시그니처",
    category: "컨디션",
    price: 31900,
    accent: "#8a7f53",
    image: "/products/product-16.jpg",
    servings: "600mg × 120정 (72g)",
    ingredients: ["알부민 아미노산 복합물 88%", "난백분 (알부민 46%) 16%"],
    features: [
      "알부민 아미노산 복합물 고배합(88%)",
      "난백분(알부민 46%)을 더한 구성",
      "간편하게 챙기는 정제 타입 · HACCP 제조",
    ],
    recommend: ["단백 섭취가 신경 쓰이는 분", "활동적인 일상을 보내는 분", "프리미엄 데일리 관리를 원하는 분"],
    intake: "1일 2정을 물과 함께 섭취하세요.",
    origin: HACCP_ORIGIN,
    caution: BASE_CAUTION + " 계란 알레르기가 있는 분은 주의하세요.",
    stock: 108,
    rating: 4.8,
    reviewCount: 149,
    subscription: { enabled: true, discountPercent: 12, intervalDays: 30 },
    badges: ["SIGNATURE", "알부민 88%"],
    isBest: true,
  },
];

const REVIEWS: Review[] = [
  { id: "r1", productId: "daily-dietary-fiber", author: "김O영", product: "데일리 식이섬유 정", rating: 5, repurchase: true, content: "채소를 잘 안 챙겨 먹는 편이라 걱정이었는데 아침저녁으로 챙기니 하루가 가벼워요. 알약도 작아서 삼키기 편합니다.", createdAt: "2026-07-24T09:12:00Z" },
  { id: "r2", productId: "triella-collagen-biotin", author: "이O준", product: "트리엘라 어린콜라겐 펩타이드", rating: 5, repurchase: true, content: "저분자라 그런지 부담 없이 먹기 좋아요. 비오틴까지 같이 들어있어서 하나로 챙길 수 있는 점이 마음에 듭니다.", createdAt: "2026-07-30T21:40:00Z" },
  { id: "r3", productId: "liposomal-glutathione", author: "박O서", product: "리포좀 글루타치온 정", rating: 5, repurchase: false, content: "요즘 컨디션 관리하려고 시작했어요. 리포좀 타입에 비타민C까지 같이 들어있어서 이 제품으로 정했습니다. 포장도 깔끔해요.", createdAt: "2026-08-05T13:05:00Z" },
  { id: "r4", productId: "acv-probiotics", author: "최O아", product: "애플사이다비니거 사과초모 유산균 정", rating: 4, repurchase: true, content: "사과초모식초 먹기 번거로웠는데 정제로 나와서 너무 편해요. 유산균까지 같이 들어있어서 아침마다 챙기고 있습니다.", createdAt: "2026-08-07T08:20:00Z" },
  { id: "r5", productId: "green-acerola-vitamin-c", author: "정O훈", product: "그린 아세로라 비타민C 원데이즈", rating: 5, repurchase: true, content: "합성 말고 아세로라 유래 비타민C를 찾고 있었어요. 원데이즈라 하루 한 알만 챙기면 돼서 잊지 않고 먹게 됩니다.", createdAt: "2026-08-09T18:30:00Z" },
  { id: "r6", productId: "fermented-oyster-kids", author: "한O림", product: "발효굴 추출분말 & 유산균 정", rating: 5, repurchase: true, content: "아이 먹이려고 샀는데 온 가족이 같이 먹고 있어요. 유산균이 22종이나 들어있어서 믿음이 갑니다. 재구매했어요!", createdAt: "2026-08-10T08:20:00Z" },
  { id: "r7", productId: "plant-melatonin-tart-cherry", author: "오O은", product: "식물성 멜라토닌 피스타치오 타트체리 정", rating: 5, repurchase: false, content: "식물성 원료라는 점이 좋아서 선택했어요. 자기 전 루틴으로 챙기고 있는데 만족스럽습니다.", createdAt: "2026-08-11T22:10:00Z" },
  { id: "r8", productId: "khorasan-grain-enzyme", author: "윤O빈", product: "프리미엄 호라산밀 곡물효소 정", rating: 4, repurchase: true, content: "카무트에 식이섬유, 효소까지 한 번에 챙길 수 있어서 좋아요. 든든하게 관리하는 느낌이라 계속 먹고 있습니다.", createdAt: "2026-08-12T11:00:00Z" },
  { id: "r9", productId: "papa-flora-ginger", author: "서O현", product: "파파 플로라 생강추출물 정", rating: 5, repurchase: true, content: "환절기마다 컨디션이 걱정이었는데 생강에 흑마늘까지 들어있어서 따뜻하게 챙기는 느낌이에요. 부모님 것도 같이 주문했습니다.", createdAt: "2026-08-13T15:45:00Z" },
];

export function getAllProducts(): Product[] {
  return PRODUCTS;
}
export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}
export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
export function getBestSellers(): Product[] {
  return PRODUCTS.filter((p) => p.isBest);
}
export function getNewArrivals(): Product[] {
  return PRODUCTS.filter((p) => p.isNew);
}
export function getCategories(): string[] {
  return Array.from(new Set(PRODUCTS.map((p) => p.category)));
}
export function getReviewsByProduct(productId: string): Review[] {
  return REVIEWS.filter((r) => r.productId === productId).sort(
    (a, b) => +new Date(b.createdAt) - +new Date(a.createdAt),
  );
}
export function getFeaturedReviews(): Review[] {
  return REVIEWS;
}
export function getSignatureProduct(): Product {
  return PRODUCTS.find((p) => p.slug === "triella-collagen-biotin") ?? PRODUCTS[0];
}
